### ISSUE TITLE
Wrong link to demo

### ISSUE THREAD

**Issue by rudnitskih** [IvanDerkach/sports-app-landing#12]
![image](https://user-images.githubusercontent.com/8848858/56799213-2413d600-6821-11e9-9c4b-f739d32f07ae.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/56799343-7228d980-6821-11e9-9ceb-ff8b368c3603.png)

**Comment by rudnitskih** [comment]
Still wrong :) Link to demo, not repo

**Comment by IvanDerkach** [comment]
first time it was on Demo) ok will change again)
