### ISSUE TITLE
Here Should be some gradient in the right of image

### ISSUE THREAD

**Issue by rudnitskih** [IvanDerkach/sports-app-landing#14]
![image](https://user-images.githubusercontent.com/8848858/56799413-95538900-6821-11e9-9045-8dd6a6379547.png)

**Comment by IvanDerkach** [comment]
а на макете же вроде нет градиента...

**Comment by rudnitskih** [comment]
Ага нет, но что-то картинка сильно выделяеться

Посмотрите как,например, у Влада это реализовано:
https://ruchkovlad.github.io/sports-app-landing/src/index.html

**Comment by IvanDerkach** [comment]
Дим, честно я не понимаю что сделать) у него бэкгрундом на див изображение, без лишних стилей,  и у меня так же) может у меня монитор что то не отображает, но как на меня 1 в 1))

**Comment by IvanDerkach** [comment]
поменял формат на png, должно быть лучше.
